import Foundation

/* 2. Придумать класс, методы которого могут выбрасывать ошибки. 
Реализуйте несколько throws-функций. 
Вызовите их и обработайте результат вызова при помощи конструкции try/catch. */

enum EmployeeErrors: Error {
    case employeeNotFound
}

class SalesDepartment {
    var employees = [
        "ivanov" : 10.25,
        "petrov" : 100.00,
        "sidorov": 50.50,
    ]
    var maxEmploeesCount: Int = 10
    
    func getEmployeeSalary(employeeName: String) throws -> Double? {
        guard let salary = employees[employeeName.lowercased()] 
        else {
            throw EmployeeErrors.employeeNotFound
        }
        return salary
    }
}

var employees = SalesDepartment()
var salary: Double?
do {
    try salary = employees.getEmployeeSalary(employeeName: "Ivanov")
} catch EmployeeErrors.employeeNotFound {
    print("Employee with name Ivanov does not exist")
}
print("Salary for Ivanov is \(salary)")

salary = nil
do {
    try salary = employees.getEmployeeSalary(employeeName: "Orlov")
} catch EmployeeErrors.employeeNotFound {
    print("Employee with name Orlov does not exist")
}

print("Salary for Orlov is \(salary)")

